### ISSUE TITLE
感谢作者！

### ISSUE THREAD

**Issue by zhou-zl18** [ethernoy/FORMS#1]
记得高一入学教育时看学长团放的《cubes》视频
爷青回😘

**Comment by sxwu11** [comment]
来晚叻…没想到有朝一日能在网上看到晒布路老校区的MC模型，感谢作者！！
可惜自己先前不知道有这个项目。窝手头有不少2005-2008年在校时期拍的乱七八糟的照片，要是之前能赶上照片征集就好了:weary:

**Comment by ethernoy** [comment]
> 来晚叻…没想到有朝一日能在网上看到晒布路老校区的MC模型，感谢作者！！ 可惜自己先前不知道有这个项目。窝手头有不少2005-2008年在校时期拍的乱七八糟的照片，要是之前能赶上照片征集就好了😩

这都能翻出来

**Comment by sxwu11** [comment]
其实是因为自己最近在维护深中的维基百科，在搜索相关信息的时候偶尔发现的。真的是很棒的项目！
